FROM node:12.1.0 as builder

WORKDIR /usr/share/nginx/html

COPY . .
ENV APP_ENV=prod
ENV API_BASE=https://links-login-api.chrove.com/api
ENV LOGIN_BASE=https://oauth.chrove.com
ENV CLIENT_ID=bf07d6d6-4d15-46ab-b5e4-6e66fac1151e
RUN yarn
RUN yarn build


FROM nginx:1.12-alpine

WORKDIR /usr/share/nginx/html
COPY --from=0 /usr/share/nginx/html/umd .

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
