name: Deploy to production

env:
  NODE_ENV: staging
  API_BASE: https://links-login-api.getlinks.jp/api
  LOGIN_BASE: https://oauth.getlinks.jp
  CLIENT_ID: 3a6c513a-a189-4586-a0f8-cba80ed84de8

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Setup node env
        uses: actions/setup-node@master
        with:
          node-version: "12.14.1"

      # build
      - run: yarn --frozen-lockfile --non-interactive

      - run: APP_ENV=${{ env.NODE_ENV }} yarn build

      # publish to worker site
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          environment: "production"
          apiToken: ${{ secrets.CF_API_TOKEN }}
